- hosts: ubuntuhillel
  vars:
    server_name: "{{ ansible_fqdn }}"
    virtualization_type: "{{ ansible_virtualization_type }}"
    package_manager: "{{ ansible_pkg_mgr }}"

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
    - name: create nginx config file
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        mode: '0644'
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: yes
